version: '3.8'
services:
  backend:
    container_name: php
    build:
        context: ./backend
        dockerfile: Dockerfile
    volumes:
      - ./backend/BookStore:/var/wwww/html
    ports:
      - '8000:80'
    
  frontend:
    container_name: node
    build:
        context: ./frontend
        dockerfile: Dockerfile
    volumes:
      - ./frontend/vite_project:/vite_project
    
  database:
    container_name: mysql
    image: mysql:5.7.37
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_DATABASE: bookstore
      MYSQL_USER: user
      MYSQL_PASSWORD: '1234'
    ports:
      - "3309:3306" 
    
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    restart: always
    environment:
      PMA_HOST: database
    depends_on:
      - database 

  server:
    container_name: nginx
    build:
        context: ./server
        dockerfile: Dockerfile

  navicat:
    image: navicat/navicatmonitor:3.0.1
    ports:
      - '3000:3000'
    depends_on:
      - database
    network_mode: "host"
    
