version: "3.8"
services:

  frontend-service:
    container_name: frontend-service
    build:
      context: ./frontend/vite_project
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    working_dir: /vite_project
    volumes:
      - ./frontend/vite_project:/vite_project
    depends_on:
      - backend-service

  nginx_react:
    container_name: nginx_react
    build: ./frontend
    command: nginx -g "daemon off;"
    ports:
      - "82:80"
    volumes:
      - ./logs/nginx-react:/var/log/nginx
      - ./frontend/vite_project:/var/www/html/vite_project
    depends_on:
      - frontend-service

  nginx_php:
    container_name: nginx_php
    build: ./backend
    command: nginx -g "daemon off;"
    ports:
      - "81:80"
    volumes:
      - ./logs/nginx-php:/var/log/nginx
      - ./backend/BookStore:/var/www/html/BookStore
    depends_on:
      - backend-service

  nginx:
    container_name: nginx
    build: ./server
    command: nginx -g "daemon off;"
    ports:
      - "80:80"
    depends_on:
      - nginx_php
      - nginx_react
      - pgadmin-service
      - ai-service
      - websocket-service
    volumes:
      - ./logs/nginx:/var/log/nginx

  backend-service:
    container_name: backend-service
    build: ./backend/BookStore
    ports:
      - "9000:9000"
    volumes:
      - ./backend/BookStore:/var/www/html/BookStore
    working_dir: /var/www/html/BookStore

  websocket-service:
    container_name: websocket-service
    build: ./websocket
    ports:
      - "8080:8080"
    volumes:
      - ./websocket:/app
    working_dir: /app
    depends_on:
      - redis-database-service

  ai-service:
    container_name: ai-service
    build: ./ai
    ports:
      - "8088:8088"
    volumes:
      - ./ai:/app
    working_dir: /app
    depends_on:
      - mongo-database
      - postgres-database-service

  database-service:
    container_name: database-service
    image: mysql:5.7.37
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: bookstore
    ports:
      - "3309:3306"
    volumes:
      - ./database:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8090:80"
    restart: always
    environment:
      PMA_HOST: database-service
    depends_on:
      - database-service

  navicat:
    image: navicat/navicatmonitor:3.0.1
    ports:
      - "3000:3000"
    depends_on:
      - database-service
    network_mode: "host"

  redis-database-service:
    container_name: redis-database-service
    image: redis:latest
    ports:
      - "6379:6379"

  redisinsight:
    container_name: redisinsight
    image: redislabs/redisinsight:latest
    ports:
      - 8001:8001
    depends_on:
      - redis-database-service
    volumes:
      - ./redisinsight:/db

  mongo-database:
    container_name: mongo-database
    image: mongo:latest
    ports:
      - "27017:27017"

  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    ports:
      - 8089:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-database
      ME_CONFIG_MONGODB_PORT: 27017
    depends_on:
      - mongo-database

  postgres-database-service:
    container_name: postgres-database-service
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${PG_ADMIN_PASS}

  pgadmin-service:
    container_name: pgadmin-service
    image: dpage/pgadmin4:latest
    ports:
      - 86:80
    environment:
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASS}
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
    depends_on:
      - postgres-database-service
