replicas:
  cv: 1
  frontend: 1
  backend: 1
  database: 1
  nginx_php: 1
  nginx_react: 1
  phpmyadmin: 0
  elasticsearch: 0
  kibana: 0

cpu:
  cv: "100m"
  frontend: "100m"
  backend: "100m"
  database: "100m"
  nginx_php: "100m"
  nginx_react: "100m"
  phpmyadmin: "100m"
  elasticsearch: "100m"
  kibana: "100m"

memory:
  cv: "300Mi"
  frontend: "300Mi"
  backend: "300Mi"
  database: "300Mi"
  nginx_php: "300Mi"
  nginx_react: "300Mi"
  phpmyadmin: "300Mi"
  elasticsearch: "300Mi"
  kibana: "300Mi"
