apiVersion: apps/v1
kind: Deployment
metadata:
  name: cv
  labels:
    app: cv
spec:
  replicas: {{ .Values.replicas.main }}
  selector:
    matchLabels:
      app: cv
  template:
    metadata:
      labels:
        app: cv
    spec:
      containers:
        - name: cv
          image: registry.gitlab.com/akherati5660/bookstore/cv:latest
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          resources:
            limits:
              memory: {{ .Values.memory.main }}
              cpu: {{ .Values.cpu.main }}
      imagePullSecrets:
        - name: key
---
apiVersion: v1
kind: Service
metadata:
  name: cv-service
spec:
  selector:
    app: cv
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30005
