apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: {{ .Values.replicas.frontend }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.images.frontend }}:{{ .Values.tag.frontend }}"
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          resources:
            limits:
              memory: {{ .Values.memory.frontend }}
              cpu: {{ .Values.cpu.frontend }}
      imagePullSecrets:
        - name: key
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - name: frontend
      port: 3000
      targetPort: 3000
