apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-object
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
  rules:
  - host: akherati5660.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cv-service
            port:
              number: 80
  - host: wwww.akherati5660.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cv-service
            port:
              number: 80
  - host: bookstore.akherati5660.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginxreact-service
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: nginxphp-service
            port:
              number: 80
  - host: monitoring.akherati5660.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: grafana-ext
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-object
  namespace: kubernetes-dashboard
spec:
  rules:
  - host: temp.dashboard.akherati5660.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kubernetes-dashboard
            port:
              number: 80





