apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxreact
  labels:
    app: nginxreact
spec:
  replicas: 0
  selector:
    matchLabels:
      app: nginxreact
  template:
    metadata:
      labels:
        app: nginxreact
    spec:
      containers:
        - name: nginxreact
          image: registry.gitlab.com/akherati5660/bookstore/nginx-react:latest
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          resources:
            limits:
              memory: "300Mi"
              cpu: "100m"
      imagePullSecrets:
        - name: key
---
apiVersion: v1
kind: Service
metadata:
  name: nginxreact-service
spec:
  selector:
    app: nginxreact
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30002
