apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
  name: argocd-server-ext
  namespace: argocd
spec:
  clusterIP: 10.98.54.214
  clusterIPs:
  - 10.98.54.214
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: port-1
    nodePort: 30184
    port: 80
    protocol: TCP
    targetPort: 443
  - name: port-2
    nodePort: 32716
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app.kubernetes.io/name: argocd-server
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
