apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-database
spec:
  replicas: { { .Values.replicas.mongo-database } }
  selector:
    matchLabels:
      app: mongo-database
  template:
    metadata:
      labels:
        app: mongo-database
    spec:
      containers:
        - name: mongo-database
          image: "{{ .Values.images.mongo-database }}:{{ .Values.tag.mongo-database }}"
          ports:
            - containerPort: 27017
          imagePullPolicy: Always
          resources:
            limits:
              memory: { { .Values.memory.mongo-database } }
              cpu: { { .Values.cpu.mongo-database } }
      imagePullSecrets:
        - name: key
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-database-service
spec:
  selector:
    app: mongo-database
  ports:
    - name: mongo-database
      port: 27017
      targetPort: 27017
