apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
spec:
  replicas: {{ .Values.replicas.mongo_express }}
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: "{{ .Values.images.mongo_express }}:{{ .Values.tag.mongo_express }}"
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_SERVER
              value: "mongo-database-service"
            - name: ME_CONFIG_MONGODB_PORT
              value: "27017"
          imagePullPolicy: Always
          resources:
            limits:
              memory: {{ .Values.memory.mongo_express }}
              cpu: {{ .Values.cpu.mongo_express }}
      imagePullSecrets:
        - name: key
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
spec:
  selector:
    app: mongo-express
  type: NodePort
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30015
