apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
spec:
  replicas: {{ .Values.replicas.pgadmin }}
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: "{{ .Values.images.pgadmin }}:{{ .Values.tag.pgadmin }}"
          ports:
            - containerPort: 80
          env:
            - name: PGADMIN_DEFAULT_PASSWORD  
              value: "1234"
            - name: PGADMIN_DEFAULT_EMAIL
              value: "akherati5660@gmail.com"
          imagePullPolicy: Always
          resources:
            limits:
              memory: {{ .Values.memory.pgadmin }}
              cpu: {{ .Values.cpu.pgadmin }}
      imagePullSecrets:
        - name: key
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
spec:
  selector:
    app: pgadmin
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30010
