apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-database
spec:
  replicas: {{ .Values.replicas.postgres_database }}
  selector:
    matchLabels:
      app: postgres-database
  template:
    metadata:
      labels:
        app: postgres-database
    spec:
      containers:
        - name: postgres-database
          image: "{{ .Values.images.postgres_database }}:{{ .Values.tag.postgres_database }}"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: "1234"
            - name: POSTGRES_DB
              value: "myproject"
          imagePullPolicy: Always
          resources:
            limits:
              memory: {{ .Values.memory.postgres_database }}
              cpu: {{ .Values.cpu.postgres_database }}
      imagePullSecrets:
        - name: key
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-database-service
spec:
  selector:
    app: postgres-database
  ports:
    - name: postgres-database
      port: 5432
      targetPort: 5432
