apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-database
spec:
  replicas: {{ .Values.replicas.postgres-database }}
  selector:
    matchLabels:
      app: postgres-database
  template:
    metadata:
      labels:
        app: postgres-database
    spec:
      containers:
        - name: postgres-database
          image: "{{ .Values.images.postgres-database }}:{{ .Values.tag.postgres-database }}"
          ports:
            - containerPort: 5432
          imagePullPolicy: Always
          resources:
            limits:
              memory: {{ .Values.memory.postgres-database }}
              cpu: {{ .Values.cpu.postgres-database }}
      imagePullSecrets:
        - name: key
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-database-service
spec:
  selector:
    app: postgres-database
  ports:
    - name: postgres-database
      port: 5432
      targetPort: 5432
