apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-database
spec:
  replicas: {{ .Values.replicas.redis_database }}
  selector:
    matchLabels:
      app: redis-database
  template:
    metadata:
      labels:
        app: redis-database
    spec:
      containers:
        - name: redis-database
          image: "{{ .Values.images.redis_database }}:{{ .Values.tag.redis_database }}"
          ports:
            - containerPort: 6379
          imagePullPolicy: Always
          resources:
            limits:
              memory: {{ .Values.memory.redis_database }}
              cpu: {{ .Values.cpu.redis_database }}
      imagePullSecrets:
        - name: key
---
apiVersion: v1
kind: Service
metadata:
  name: redis-database-service
spec:
  selector:
    app: redis-database
  ports:
    - name: redis-database
      port: 6379
      targetPort: 6379
