images:
  cv: "registry.gitlab.com/akherati5660/bookstore/cv"
  frontend: "registry.gitlab.com/akherati5660/bookstore/frontend"
  backend: "registry.gitlab.com/akherati5660/bookstore/backend"
  database: "mysql"
  nginx_php: "registry.gitlab.com/akherati5660/bookstore/nginx-php"
  nginx_react: "registry.gitlab.com/akherati5660/bookstore/nginx-react"
  phpmyadmin: "phpmyadmin/phpmyadmin"
  elasticsearch: "latest"
  kibana: "latest"
  websocket: "registry.gitlab.com/akherati5660/bookstore/websocket"
  ai: "registry.gitlab.com/akherati5660/bookstore/ai"
  redis_database: "redis"
  mongo_database: "mongo"
  postgres_database: "postgres"
  mongo_express: "mongo-express"
  redisinsight: "redislabs/redisinsight"
  pgadmin: "dpage/pgadmin4"

tag:
  cv: "v1.0.6"
  frontend: "v1.0.6"
  backend: "v1.0.6"
  database: "5.7"
  nginx_php: "v1.0.6"
  nginx_react: "v1.0.6"
  websocket: "v1.0.6"
  ai: "v1.0.6"
  phpmyadmin: "latest"
  elasticsearch: "latest"
  kibana: "latest"
  redis_database: "latest"
  mongo_database: "latest"
  postgres_database: "latest"
  mongo_express: "latest"
  redisinsight: "latest"
  pgadmin: "latest"

replicas:
  cv: 0
  frontend: 0
  backend: 0
  database: 0
  nginx_php: 0
  nginx_react: 0
  phpmyadmin: 0
  elasticsearch: 0
  kibana: 0
  websocket: 0
  ai: 0
  redis_database: 1
  mongo_database: 1
  postgres_database: 1
  mongo_express: 1
  redisinsight: 1
  pgadmin: 0

cpu:
  cv: "80m"
  frontend: "80m"
  backend: "80m"
  database: "80m"
  nginx_php: "80m"
  nginx_react: "80m"
  phpmyadmin: "80m"
  elasticsearch: "80m"
  kibana: "80m"
  websocket: "80m"
  ai: "80m"
  redis_database: "80m"
  mongo_database: "80m"
  postgres_database: "80m"
  mongo_express: "80m"
  redisinsight: "80m"
  pgadmin: "80m"

memory:
  cv: "300Mi"
  frontend: "300Mi"
  backend: "300Mi"
  database: "300Mi"
  nginx_php: "300Mi"
  nginx_react: "300Mi"
  phpmyadmin: "300Mi"
  elasticsearch: "300Mi"
  kibana: "300Mi"
  websocket: "300Mi"
  ai: "300Mi"
  redis_database: "300Mi"
  mongo_database: "300Mi"
  postgres_database: "300Mi"
  mongo_express: "300Mi"
  redisinsight: "300Mi"
  pgadmin: "300Mi"
