images:
  cv: "registry.gitlab.com/akherati5660/bookstore/cv"
  frontend: "registry.gitlab.com/akherati5660/bookstore/frontend"
  backend: "registry.gitlab.com/akherati5660/bookstore/backend"
  database: "mysql"
  nginx_php: "registry.gitlab.com/akherati5660/bookstore/nginx-php"
  nginx_react: "registry.gitlab.com/akherati5660/bookstore/nginx-react"
  phpmyadmin: "phpmyadmin/phpmyadmin"
  elasticsearch: "latest"
  kibana: "latest"

tag:
  cv: "v1.0.2"
  frontend: "v1.0.2"
  backend: "v1.0.2"
  database: "5.7"
  nginx_php: "v1.0.2"
  nginx_react: "v1.0.2"
  phpmyadmin: "latest"
  elasticsearch: "latest"
  kibana: "latest"

replicas:
  cv: 1
  frontend: 1
  backend: 1
  database: 1
  nginx_php: 1
  nginx_react: 1
  phpmyadmin: 1
  elasticsearch: 0
  kibana: 0

cpu:
  cv: "100m"
  frontend: "100m"
  backend: "100m"
  database: "100m"
  nginx_php: "100m"
  nginx_react: "100m"
  phpmyadmin: "100m"
  elasticsearch: "100m"
  kibana: "100m"

memory:
  cv: "300Mi"
  frontend: "300Mi"
  backend: "300Mi"
  database: "300Mi"
  nginx_php: "300Mi"
  nginx_react: "300Mi"
  phpmyadmin: "300Mi"
  elasticsearch: "300Mi"
  kibana: "300Mi"
