
upstream laravel_upstream {
	server 127.0.0.1:81; # Replace with your Laravel Nginx IP and port
}

upstream react_upstream {
	server 127.0.0.1:80; # Replace with your React Nginx IP and port
}

server {
	listen 80; # Change this to the port you want Nginx to listen on

	location / {
		proxy_pass http://react_upstream;
	}

	location /api {
		proxy_pass http://laravel_upstream;
	}
}
